// Banco temático de perguntas por destino.
// Cada destino tem 30 perguntas distribuídas em 3 níveis de dificuldade (10 por nível).
// Nível 1 = fácil (cultura geral / pop), 2 = médio (curiosidade conhecida), 3 = difícil (detalhe verificável).
// Todas as respostas podem ser confirmadas com uma busca rápida no Google.

export interface BankQuestion { q: string; choices: string[]; answer: number; level: 1 | 2 | 3 }

const BANK: Record<string, BankQuestion[]> = {
  mercurio: [
    // nível 1 (fácil)
    { level: 1, q: "Mercúrio é o planeta mais próximo de quê?", choices: ["Lua", "Sol", "Terra", "Marte"], answer: 1 },
    { level: 1, q: "Mercúrio é maior ou menor que a Terra?", choices: ["Muito maior", "Igual", "Menor", "Tamanho de Júpiter"], answer: 2 },
    { level: 1, q: "Qual a cor predominante de Mercúrio?", choices: ["Azul", "Cinza", "Verde", "Rosa"], answer: 1 },
    { level: 1, q: "Mercúrio tem oceanos de água?", choices: ["Sim, vários", "Não", "Só um", "Só nos polos"], answer: 1 },
    { level: 1, q: "Mercúrio é um planeta:", choices: ["Rochoso", "Gasoso", "De gelo", "De lava"], answer: 0 },
    { level: 1, q: "O nome Mercúrio vem de qual mitologia?", choices: ["Egípcia", "Nórdica", "Romana", "Japonesa"], answer: 2 },
    { level: 1, q: "Quantas luas Mercúrio tem?", choices: ["0", "1", "2", "5"], answer: 0 },
    { level: 1, q: "Mercúrio tem atmosfera densa como a da Terra?", choices: ["Sim", "Não, é praticamente nula", "Sim, de oxigênio", "Sim, só à noite"], answer: 1 },
    { level: 1, q: "Mercúrio é visível a olho nu da Terra?", choices: ["Sim, perto do Sol", "Não, nunca", "Só com telescópio espacial", "Só de avião"], answer: 0 },
    { level: 1, q: "Qual a posição de Mercúrio no Sistema Solar?", choices: ["1º", "2º", "3º", "Último"], answer: 0 },
    // nível 2 (médio)
    { level: 2, q: "Quanto dura um ano em Mercúrio (aprox.)?", choices: ["88 dias terrestres", "1 ano terrestre", "10 anos", "30 dias"], answer: 0 },
    { level: 2, q: "Qual a característica marcante da superfície de Mercúrio?", choices: ["Oceanos azuis", "Florestas", "Crateras como a da Lua", "Anéis de gelo"], answer: 2 },
    { level: 2, q: "Por que Mercúrio tem variação de temperatura extrema?", choices: ["Atmosfera densa", "Atmosfera quase inexistente", "Anéis refletivos", "Vegetação"], answer: 1 },
    { level: 2, q: "Mercúrio chegou a ser visitado por qual sonda da NASA?", choices: ["Voyager 1", "Messenger", "Cassini", "Juno"], answer: 1 },
    { level: 2, q: "Qual planeta era considerado mais quente até descobrirem Vênus?", choices: ["Mercúrio", "Marte", "Saturno", "Plutão"], answer: 0 },
    { level: 2, q: "Mercúrio é o ___ menor planeta do Sistema Solar.", choices: ["1º (o menor)", "2º", "3º", "Último"], answer: 0 },
    { level: 2, q: "Em mitologia romana, Mercúrio era deus de quê?", choices: ["Guerra", "Comércio e mensageiros", "Amor", "Mar"], answer: 1 },
    { level: 2, q: "A temperatura à noite em Mercúrio pode chegar a quanto?", choices: ["0 °C", "-180 °C", "100 °C", "30 °C"], answer: 1 },
    { level: 2, q: "Mercúrio tem anéis visíveis como Saturno?", choices: ["Sim, três", "Não", "Sim, gigantes", "Sim, de gelo"], answer: 1 },
    { level: 2, q: "Mercúrio gira muito lentamente em torno de si mesmo?", choices: ["Sim, leva ~59 dias terrestres", "Não, gira em 1h", "Não gira", "Gira em 12h"], answer: 0 },
    // nível 3 (difícil)
    { level: 3, q: "Qual sonda foi a 1ª a entrar em órbita de Mercúrio?", choices: ["Mariner 10", "Messenger", "BepiColombo", "Voyager 2"], answer: 1 },
    { level: 3, q: "Quem opera a missão BepiColombo, em viagem a Mercúrio?", choices: ["NASA + ESA + JAXA", "Roscosmos", "SpaceX", "ISRO"], answer: 0 },
    { level: 3, q: "Qual é a maior cratera de impacto conhecida em Mercúrio?", choices: ["Caloris", "Tycho", "Hellas", "Aitken"], answer: 0 },
    { level: 3, q: "Mercúrio tem campo magnético global?", choices: ["Sim, fraco", "Não tem nenhum", "Sim, mais forte que o da Terra", "Apenas nos polos"], answer: 0 },
    { level: 3, q: "Mercúrio é o planeta mais ___ do Sistema Solar.", choices: ["Mais quente", "Menor e mais próximo do Sol", "Maior", "Mais frio"], answer: 1 },
    { level: 3, q: "Existe gelo de água em Mercúrio?", choices: ["Sim, em crateras polares", "Não, é impossível", "Só no equador", "Só em luas"], answer: 0 },
    { level: 3, q: "Mercúrio leva quanto tempo para completar um dia solar?", choices: ["176 dias terrestres", "1 dia terrestre", "24 horas", "1 ano"], answer: 0 },
    { level: 3, q: "A densidade de Mercúrio é alta porque ele tem grande núcleo de:", choices: ["Ouro", "Ferro", "Gelo", "Gás"], answer: 1 },
    { level: 3, q: "Quem foi o primeiro astrônomo a observar Mercúrio com telescópio?", choices: ["Galileu", "Newton", "Hubble", "Kepler"], answer: 0 },
    { level: 3, q: "Mercúrio aparece em qual ópera/obra famosa de Holst?", choices: ["Os Planetas", "Carmen", "A Flauta Mágica", "Bolero"], answer: 0 },
  ],
  venus: [
    { level: 1, q: "Vênus é conhecido como planeta gêmeo de qual outro?", choices: ["Marte", "Terra", "Júpiter", "Saturno"], answer: 1 },
    { level: 1, q: "Vênus é famoso por ser extremamente:", choices: ["Frio", "Quente", "Úmido", "Verde"], answer: 1 },
    { level: 1, q: "Qual deusa dá nome a Vênus?", choices: ["Da guerra", "Do amor e beleza", "Da caça", "Do mar"], answer: 1 },
    { level: 1, q: "Vênus é visível da Terra como:", choices: ["Estrela d'alva", "Cometa", "Buraco negro", "Galáxia"], answer: 0 },
    { level: 1, q: "Vênus é um planeta:", choices: ["Rochoso", "Gasoso", "De gelo", "Anão"], answer: 0 },
    { level: 1, q: "Qual a cor que dá nome ao brilho de Vênus no céu?", choices: ["Vermelho", "Branco brilhante", "Azul", "Verde"], answer: 1 },
    { level: 1, q: "Vênus tem quantas luas?", choices: ["0", "1", "2", "10"], answer: 0 },
    { level: 1, q: "Vênus é o ___ planeta do Sistema Solar.", choices: ["1º", "2º", "3º", "4º"], answer: 1 },
    { level: 1, q: "A atmosfera de Vênus é feita principalmente de:", choices: ["Oxigênio", "Dióxido de carbono", "Hélio", "Água"], answer: 1 },
    { level: 1, q: "Vênus tem anéis como Saturno?", choices: ["Sim", "Não", "Só de gelo", "Só 1 grande"], answer: 1 },
    { level: 2, q: "Vênus gira em qual sentido em relação à maioria dos planetas?", choices: ["Mesmo sentido", "Sentido contrário", "Não gira", "De lado"], answer: 1 },
    { level: 2, q: "A pressão na superfície de Vênus é ~ quantas vezes a da Terra?", choices: ["1×", "10×", "90×", "1000×"], answer: 2 },
    { level: 2, q: "Quanto dura um ano em Vênus (aprox.)?", choices: ["225 dias", "1 ano", "10 anos", "30 dias"], answer: 0 },
    { level: 2, q: "Vênus é mais quente que Mercúrio por causa do:", choices: ["Sol direto", "Efeito estufa", "Núcleo de fogo", "Vento solar"], answer: 1 },
    { level: 2, q: "As nuvens de Vênus contêm ácido:", choices: ["Sulfúrico", "Clorídrico", "Cítrico", "Nenhum"], answer: 0 },
    { level: 2, q: "Vênus foi visitado por qual programa soviético?", choices: ["Soyuz", "Venera", "Vostok", "Mir"], answer: 1 },
    { level: 2, q: "Vênus aparece em uma famosa pintura de:", choices: ["Botticelli (O Nascimento de Vênus)", "Da Vinci", "Picasso", "Monet"], answer: 0 },
    { level: 2, q: "Vênus pode ser vista de manhã ou à noite. Qual nome popular?", choices: ["Estrela da Manhã / da Tarde", "Estrela do Sul", "Estrela do Pastor", "Estrela Cadente"], answer: 0 },
    { level: 2, q: "A temperatura na superfície de Vênus passa de:", choices: ["50 °C", "100 °C", "460 °C", "1000 °C"], answer: 2 },
    { level: 2, q: "Vênus é maior, menor ou do tamanho da Terra?", choices: ["Maior", "Menor mas parecido", "Muito menor", "Igual ao Sol"], answer: 1 },
    { level: 3, q: "Qual sonda da ESA orbitou Vênus de 2006 a 2014?", choices: ["Venus Express", "Mariner 2", "Magellan", "BepiColombo"], answer: 0 },
    { level: 3, q: "Qual sonda da NASA mapeou Vênus por radar nos anos 1990?", choices: ["Magellan", "Galileo", "Cassini", "Juno"], answer: 0 },
    { level: 3, q: "Quem foi a 1ª a pousar em Vênus (anos 70)?", choices: ["NASA", "Venera 7 (URSS)", "ESA", "China"], answer: 1 },
    { level: 3, q: "Qual a duração de um dia sideral em Vênus?", choices: ["~24 h", "~243 dias terrestres", "1 ano", "1 hora"], answer: 1 },
    { level: 3, q: "Vênus possui campo magnético global forte?", choices: ["Sim, gigante", "Não, é praticamente sem", "Sim, igual ao da Terra", "Sim, com 2 polos extras"], answer: 1 },
    { level: 3, q: "O ponto mais alto de Vênus se chama:", choices: ["Maxwell Montes", "Olympus Mons", "Mons Huygens", "Pico do Sol"], answer: 0 },
    { level: 3, q: "Vênus completa um ano (translação) em quantos dias?", choices: ["88", "225", "365", "687"], answer: 1 },
    { level: 3, q: "Vênus tem mais vulcões catalogados que a Terra?", choices: ["Sim", "Não", "Tem zero", "Só extintos"], answer: 0 },
    { level: 3, q: "A próxima missão da NASA para Vênus se chama:", choices: ["DAVINCI / VERITAS", "Europa Clipper", "Dragonfly", "JUICE"], answer: 0 },
    { level: 3, q: "Vênus tem ____ que ajuda a girar tão devagar.", choices: ["Atmosfera super densa", "Lua gigante", "Anel grosso", "Vento solar fraco"], answer: 0 },
  ],
  marte: [
    { level: 1, q: "Marte é conhecido como Planeta:", choices: ["Azul", "Vermelho", "Verde", "Branco"], answer: 1 },
    { level: 1, q: "Em 'Perdido em Marte', qual planta o astronauta cultiva?", choices: ["Tomate", "Batata", "Milho", "Alface"], answer: 1 },
    { level: 1, q: "Marte é o ___ planeta do Sol.", choices: ["1º", "2º", "3º", "4º"], answer: 3 },
    { level: 1, q: "Marte é maior ou menor que a Terra?", choices: ["Maior", "Menor", "Igual", "Tamanho de Júpiter"], answer: 1 },
    { level: 1, q: "Qual empresa de Elon Musk planeja levar humanos a Marte?", choices: ["Tesla", "SpaceX", "Boring", "Neuralink"], answer: 1 },
    { level: 1, q: "Marte recebe nome do deus romano da:", choices: ["Guerra", "Beleza", "Sabedoria", "Caça"], answer: 0 },
    { level: 1, q: "Marte tem atmosfera respirável para humanos?", choices: ["Sim", "Não", "Sim, com filtro simples", "Só de noite"], answer: 1 },
    { level: 1, q: "Marte tem gelo nos polos?", choices: ["Sim", "Não", "Só no equador", "Só ao meio-dia"], answer: 0 },
    { level: 1, q: "Marte é um planeta:", choices: ["Rochoso", "Gasoso", "De gelo", "Estrela"], answer: 0 },
    { level: 1, q: "Marte é vizinho de quais planetas?", choices: ["Mercúrio e Vênus", "Terra e Júpiter", "Saturno e Urano", "Plutão e Netuno"], answer: 1 },
    { level: 2, q: "Quantas luas Marte possui?", choices: ["0", "1", "2", "10"], answer: 2 },
    { level: 2, q: "Como se chamam as duas luas de Marte?", choices: ["Fobos e Deimos", "Lua e Sol", "Titã e Europa", "Caronte e Tritão"], answer: 0 },
    { level: 2, q: "Qual o nome do maior vulcão de Marte (e do Sistema Solar)?", choices: ["Olympus Mons", "Vesúvio", "Fuji", "Etna"], answer: 0 },
    { level: 2, q: "A cor vermelha de Marte vem de:", choices: ["Plantas", "Óxido de ferro (ferrugem)", "Lava", "Areia preta"], answer: 1 },
    { level: 2, q: "Marte tem o maior cânion do Sistema Solar. Nome?", choices: ["Valles Marineris", "Grand Canyon", "Bryce Canyon", "Olympus Canyon"], answer: 0 },
    { level: 2, q: "Quanto dura um ano marciano?", choices: ["365 dias", "687 dias terrestres", "100 dias", "10 anos"], answer: 1 },
    { level: 2, q: "Um dia marciano (sol) dura aproximadamente:", choices: ["24 h e 39 min", "1 h", "12 h", "48 h"], answer: 0 },
    { level: 2, q: "Marte tem evidência forte de água ___ no passado.", choices: ["Líquida", "Sólida apenas", "Gasosa apenas", "Nenhuma"], answer: 0 },
    { level: 2, q: "Em Marte, a gravidade é cerca de quanto da terrestre?", choices: ["38%", "100%", "200%", "10%"], answer: 0 },
    { level: 2, q: "Marte aparece em qual filme de Ridley Scott de 2015?", choices: ["Perdido em Marte", "Gravidade", "Interestelar", "Apollo 13"], answer: 0 },
    { level: 3, q: "Quem foi o 1º rover a operar com sucesso em Marte (1997)?", choices: ["Sojourner", "Curiosity", "Spirit", "Perseverance"], answer: 0 },
    { level: 3, q: "O rover Perseverance pousou em Marte em:", choices: ["2018", "2021", "2015", "2024"], answer: 1 },
    { level: 3, q: "Qual helicóptero voou em Marte com a NASA?", choices: ["Ingenuity", "Falcon", "Apache", "Drone-1"], answer: 0 },
    { level: 3, q: "A cratera onde Perseverance pousou se chama:", choices: ["Jezero", "Gale", "Tycho", "Hellas"], answer: 0 },
    { level: 3, q: "Curiosity pousou em qual cratera, em 2012?", choices: ["Gale", "Jezero", "Endeavour", "Tycho"], answer: 0 },
    { level: 3, q: "A atmosfera de Marte é feita principalmente de:", choices: ["Nitrogênio", "Oxigênio", "Dióxido de carbono", "Hidrogênio"], answer: 2 },
    { level: 3, q: "A pressão atmosférica em Marte é cerca de ___ % da da Terra.", choices: ["0,6 %", "50 %", "100 %", "200 %"], answer: 0 },
    { level: 3, q: "Qual escritor escreveu 'Crônicas Marcianas'?", choices: ["Ray Bradbury", "Isaac Asimov", "Stephen King", "J. K. Rowling"], answer: 0 },
    { level: 3, q: "Qual agência operou as missões Viking, 1ª a pousar em Marte (1976)?", choices: ["NASA", "ESA", "Roscosmos", "JAXA"], answer: 0 },
    { level: 3, q: "Tempestades de poeira em Marte podem cobrir:", choices: ["Apenas 1 cratera", "Quase o planeta inteiro", "Só os polos", "Só o equador"], answer: 1 },
  ],
  jupiter: [
    { level: 1, q: "Júpiter é o ___ planeta do Sistema Solar.", choices: ["Menor", "Maior", "Mais frio", "Mais próximo do Sol"], answer: 1 },
    { level: 1, q: "Júpiter tem uma tempestade gigante chamada:", choices: ["Olho do Furacão", "Grande Mancha Vermelha", "Tornado Azul", "Buraco Branco"], answer: 1 },
    { level: 1, q: "Júpiter é um planeta:", choices: ["Rochoso", "Gasoso", "De gelo", "De fogo"], answer: 1 },
    { level: 1, q: "Júpiter recebeu nome de qual deus romano?", choices: ["Da guerra", "Rei dos deuses", "Do mar", "Do amor"], answer: 1 },
    { level: 1, q: "Júpiter tem anéis?", choices: ["Sim, finos e pouco visíveis", "Não tem", "Sim, gigantes como Saturno", "Sim, de fogo"], answer: 0 },
    { level: 1, q: "Júpiter é maior ou menor que a Terra?", choices: ["Maior", "Menor", "Igual", "Igual ao Sol"], answer: 0 },
    { level: 1, q: "Júpiter é majoritariamente feito de:", choices: ["Pedra e ferro", "Água", "Hidrogênio e hélio", "Gelo"], answer: 2 },
    { level: 1, q: "Júpiter aparece em filme da Disney/Pixar como nome de:", choices: ["Wall-E", "personagem em Soul ou Inside Out (referências)", "Lightyear", "carro de Carros"], answer: 1 },
    { level: 1, q: "Júpiter pode ser visto a olho nu da Terra?", choices: ["Sim, é bem brilhante", "Não, nunca", "Só de avião", "Só com Hubble"], answer: 0 },
    { level: 1, q: "Júpiter tem muitas luas?", choices: ["Sim, dezenas", "Não, só 1", "Nenhuma", "Só 2"], answer: 0 },
    { level: 2, q: "Qual destas é uma lua de Júpiter?", choices: ["Europa", "Titã", "Lua", "Fobos"], answer: 0 },
    { level: 2, q: "Quem descobriu as 4 maiores luas de Júpiter?", choices: ["Galileu Galilei", "Newton", "Einstein", "Kepler"], answer: 0 },
    { level: 2, q: "As 4 luas galileanas são Io, Europa, Ganimedes e:", choices: ["Calisto", "Titã", "Lua", "Tritão"], answer: 0 },
    { level: 2, q: "A maior lua do Sistema Solar é:", choices: ["Ganimedes", "Lua", "Titã", "Europa"], answer: 0 },
    { level: 2, q: "Júpiter completa um ano em quanto tempo?", choices: ["~12 anos terrestres", "1 ano", "100 anos", "30 dias"], answer: 0 },
    { level: 2, q: "Quanto dura um dia em Júpiter?", choices: ["~10 horas", "24 horas", "1 semana", "1 ano"], answer: 0 },
    { level: 2, q: "Júpiter é tão massivo que ___ a maioria dos planetas juntos.", choices: ["Mais massa que", "Mesma massa que", "Menos massa que", "Igual à Lua"], answer: 0 },
    { level: 2, q: "Io, lua de Júpiter, é famosa por:", choices: ["Vulcanismo intenso", "Florestas", "Oceanos azuis", "Cidades"], answer: 0 },
    { level: 2, q: "Europa, lua de Júpiter, pode ter:", choices: ["Oceano sob o gelo", "Florestas", "Lava", "Pirâmides"], answer: 0 },
    { level: 2, q: "Júpiter é mais perto ou mais longe do Sol que Marte?", choices: ["Mais perto", "Mais longe", "Mesma distância", "Dentro de Marte"], answer: 1 },
    { level: 3, q: "Qual sonda da NASA orbita Júpiter desde 2016?", choices: ["Juno", "Cassini", "Voyager 2", "Pioneer 10"], answer: 0 },
    { level: 3, q: "Qual missão da ESA partiu rumo a luas de Júpiter em 2023?", choices: ["JUICE", "BepiColombo", "Rosetta", "Mars Express"], answer: 0 },
    { level: 3, q: "Quem foi a 1ª sonda a passar por Júpiter (1973)?", choices: ["Pioneer 10", "Voyager 1", "Cassini", "Galileo"], answer: 0 },
    { level: 3, q: "A Grande Mancha Vermelha existe há pelo menos:", choices: ["100 anos", "10 anos", "350+ anos", "1 ano"], answer: 2 },
    { level: 3, q: "Júpiter tem campo magnético muito mais forte que o da Terra?", choices: ["Sim, muito mais", "Não, mais fraco", "Igual", "Não tem"], answer: 0 },
    { level: 3, q: "O núcleo de Júpiter provavelmente é:", choices: ["Rochoso/metálico denso", "De diamante puro", "De plástico", "Vazio"], answer: 0 },
    { level: 3, q: "A camada profunda de Júpiter contém hidrogênio:", choices: ["Metálico líquido", "Sólido", "Gasoso apenas", "Plasma de fogo"], answer: 0 },
    { level: 3, q: "Júpiter foi atingido em 1994 pelo cometa:", choices: ["Shoemaker-Levy 9", "Halley", "Hale-Bopp", "Neowise"], answer: 0 },
    { level: 3, q: "A sonda Galileo da NASA terminou caindo em:", choices: ["Júpiter", "Terra", "Lua", "Sol"], answer: 0 },
    { level: 3, q: "Em mitologia, Ganimedes era ___ de Júpiter (Zeus).", choices: ["Copeiro", "Inimigo", "Pai", "Irmão"], answer: 0 },
  ],
  saturno: [
    { level: 1, q: "Saturno é famoso por ter:", choices: ["Vida", "Anéis visíveis", "Florestas", "Oceanos"], answer: 1 },
    { level: 1, q: "Saturno é um planeta:", choices: ["Rochoso", "Gasoso", "De gelo puro", "De fogo"], answer: 1 },
    { level: 1, q: "Saturno é o ___ maior planeta do Sistema Solar.", choices: ["Primeiro", "Segundo", "Terceiro", "Último"], answer: 1 },
    { level: 1, q: "Saturno pode ser visto da Terra a olho nu?", choices: ["Sim", "Não", "Só com Hubble", "Só de avião"], answer: 0 },
    { level: 1, q: "Saturno recebe nome do deus romano:", choices: ["Da guerra", "Do tempo / agricultura", "Do amor", "Do mar"], answer: 1 },
    { level: 1, q: "Saturno é maior que a Terra?", choices: ["Muito maior", "Menor", "Igual", "Igual à Lua"], answer: 0 },
    { level: 1, q: "Saturno tem muitas luas?", choices: ["Sim, mais de 80 confirmadas", "Não, só 1", "Nenhuma", "Só 2"], answer: 0 },
    { level: 1, q: "Saturno fica entre quais planetas?", choices: ["Júpiter e Urano", "Terra e Marte", "Plutão e Netuno", "Sol e Vênus"], answer: 0 },
    { level: 1, q: "O símbolo astrológico de Saturno parece:", choices: ["Uma foice", "Um coração", "Uma estrela", "Um sol"], answer: 0 },
    { level: 1, q: "Saturno é parecido em composição com qual planeta?", choices: ["Júpiter", "Marte", "Mercúrio", "Vênus"], answer: 0 },
    { level: 2, q: "Os anéis de Saturno são feitos principalmente de:", choices: ["Metal", "Gelo e rocha", "Plástico", "Gás"], answer: 1 },
    { level: 2, q: "Qual a maior lua de Saturno?", choices: ["Europa", "Titã", "Lua", "Fobos"], answer: 1 },
    { level: 2, q: "Titã é famosa por ter:", choices: ["Atmosfera densa e lagos de metano", "Florestas", "Oceano de chocolate", "Cidades"], answer: 0 },
    { level: 2, q: "Saturno demora quantos anos terrestres para uma volta no Sol?", choices: ["~29 anos", "1 ano", "100 anos", "1000 anos"], answer: 0 },
    { level: 2, q: "Saturno tem densidade tão baixa que:", choices: ["Flutuaria em água (em teoria)", "Afundaria como pedra", "Pesa como ouro", "Pesa como chumbo"], answer: 0 },
    { level: 2, q: "Quem descobriu os anéis de Saturno?", choices: ["Galileu (depois descrito por Huygens)", "Newton", "Einstein", "Kepler"], answer: 0 },
    { level: 2, q: "Saturno tem hexágono curioso em qual polo?", choices: ["Polo Norte", "Polo Sul", "Equador", "Não tem hexágono"], answer: 0 },
    { level: 2, q: "Enceladus, lua de Saturno, expele:", choices: ["Jatos de água/vapor", "Lava", "Fogo", "Fumaça preta"], answer: 0 },
    { level: 2, q: "Saturno tem campo magnético?", choices: ["Sim", "Não", "Só em luas", "Só nos anéis"], answer: 0 },
    { level: 2, q: "Os anéis de Saturno têm espessura, em geral, de poucas:", choices: ["Dezenas de metros", "Centenas de quilômetros", "Milhões de km", "Nenhum, são imaginários"], answer: 0 },
    { level: 3, q: "Qual sonda orbitou Saturno de 2004 a 2017?", choices: ["Cassini", "Voyager 1", "Juno", "Galileo"], answer: 0 },
    { level: 3, q: "Quem foi a 1ª sonda a passar por Saturno (1979)?", choices: ["Pioneer 11", "Voyager 1", "Cassini", "Mariner 10"], answer: 0 },
    { level: 3, q: "A sonda Huygens (ESA) pousou em qual lua?", choices: ["Titã", "Europa", "Lua", "Fobos"], answer: 0 },
    { level: 3, q: "Saturno é o planeta de número ___ a partir do Sol.", choices: ["6º", "5º", "7º", "8º"], answer: 0 },
    { level: 3, q: "O dia em Saturno dura aproximadamente:", choices: ["10,5 horas", "24 horas", "1 semana", "1 ano"], answer: 0 },
    { level: 3, q: "Quem nomeou o hexágono de Saturno em homenagem a ele?", choices: ["É descoberto por Voyager/Cassini", "Galileu", "Einstein", "Newton"], answer: 0 },
    { level: 3, q: "A próxima grande missão para Titã será:", choices: ["Dragonfly", "Europa Clipper", "JUICE", "BepiColombo"], answer: 0 },
    { level: 3, q: "Saturno tem divisão famosa entre seus anéis chamada:", choices: ["Divisão de Cassini", "Divisão de Newton", "Divisão de Kepler", "Divisão de Einstein"], answer: 0 },
    { level: 3, q: "Saturno é classificado como:", choices: ["Gigante gasoso", "Anão", "Rochoso", "Estrela"], answer: 0 },
    { level: 3, q: "Em mitologia romana, Saturno era pai de qual deus?", choices: ["Júpiter", "Marte", "Vênus", "Mercúrio"], answer: 0 },
  ],
  urano: [
    { level: 1, q: "Urano tem qual cor predominante?", choices: ["Vermelho", "Azul-esverdeado", "Amarelo", "Preto"], answer: 1 },
    { level: 1, q: "Urano gira de um jeito incomum porque está:", choices: ["Em pé", "Deitado de lado", "Parado", "Ao contrário"], answer: 1 },
    { level: 1, q: "Urano é o ___ planeta do Sol.", choices: ["6º", "7º", "8º", "9º"], answer: 1 },
    { level: 1, q: "Urano é maior ou menor que a Terra?", choices: ["Maior", "Menor", "Igual", "Igual à Lua"], answer: 0 },
    { level: 1, q: "Urano é um planeta:", choices: ["Rochoso", "Gigante gelado", "Estrela", "Anão"], answer: 1 },
    { level: 1, q: "Urano tem anéis?", choices: ["Sim, mas pouco visíveis", "Não tem nenhum", "Tem só 1 grande", "Mais que Saturno"], answer: 0 },
    { level: 1, q: "Urano recebe nome de qual deus?", choices: ["Grego do céu", "Romano da guerra", "Egípcio do Sol", "Nórdico do trovão"], answer: 0 },
    { level: 1, q: "Urano é visível a olho nu da Terra?", choices: ["Quase, em locais muito escuros", "Sim, brilhante", "Não, impossível", "Só de dia"], answer: 0 },
    { level: 1, q: "Urano fica antes ou depois de Netuno?", choices: ["Antes", "Depois", "No mesmo lugar", "Dentro de Netuno"], answer: 0 },
    { level: 1, q: "Urano fica antes ou depois de Saturno?", choices: ["Antes", "Depois", "Mesma órbita", "Dentro de Saturno"], answer: 1 },
    { level: 2, q: "Quem descobriu Urano em 1781?", choices: ["Galileu", "William Herschel", "Newton", "Einstein"], answer: 1 },
    { level: 2, q: "Urano leva quantos anos terrestres para 1 volta no Sol?", choices: ["~84 anos", "1 ano", "10 anos", "1000 anos"], answer: 0 },
    { level: 2, q: "A cor azul-esverdeada de Urano vem principalmente de:", choices: ["Metano na atmosfera", "Água", "Algas", "Ferro"], answer: 0 },
    { level: 2, q: "Urano tem quantas luas conhecidas (>20)?", choices: ["Mais de 20", "1", "0", "5"], answer: 0 },
    { level: 2, q: "As luas de Urano têm nomes inspirados em obras de:", choices: ["Shakespeare e Pope", "Bíblia", "Mitologia grega", "Disney"], answer: 0 },
    { level: 2, q: "Uma das maiores luas de Urano é:", choices: ["Titânia", "Titã", "Europa", "Lua"], answer: 0 },
    { level: 2, q: "Urano e Netuno são classificados como gigantes:", choices: ["Gelados", "Gasosos quentes", "Rochosos", "Estrelas"], answer: 0 },
    { level: 2, q: "Urano tem ventos rápidos?", choices: ["Sim, fortíssimos", "Não, é calmo", "Nenhum", "Só nos polos"], answer: 0 },
    { level: 2, q: "Urano gira ao contrário (retrógrado)?", choices: ["Sim", "Não", "Parou de girar", "Só em luas"], answer: 0 },
    { level: 2, q: "A temperatura em Urano é uma das mais ___ do Sistema Solar.", choices: ["Frias", "Quentes", "Médias", "Mornas"], answer: 0 },
    { level: 3, q: "Qual única sonda da NASA passou por Urano (1986)?", choices: ["Voyager 2", "Voyager 1", "Cassini", "Juno"], answer: 0 },
    { level: 3, q: "Urano foi o 1º planeta descoberto com:", choices: ["Telescópio", "A olho nu", "Por sonda", "Por satélite"], answer: 0 },
    { level: 3, q: "O nome Urano foi sugerido por:", choices: ["Johann Bode", "Newton", "Galileu", "Hubble"], answer: 0 },
    { level: 3, q: "Urano tem inclinação axial de aproximadamente:", choices: ["98°", "23°", "0°", "180°"], answer: 0 },
    { level: 3, q: "Urano tem cinturão de radiação intenso?", choices: ["Sim", "Não", "Só na sombra", "Só ao meio-dia"], answer: 0 },
    { level: 3, q: "Quanto dura 1 dia em Urano?", choices: ["~17 horas", "24 horas", "1 semana", "1 mês"], answer: 0 },
    { level: 3, q: "A maior lua de Urano se chama:", choices: ["Titânia", "Lua", "Tritão", "Europa"], answer: 0 },
    { level: 3, q: "Urano e Netuno provavelmente têm interior rico em:", choices: ["Água, metano e amônia (gelos)", "Plástico", "Ouro puro", "Vácuo"], answer: 0 },
    { level: 3, q: "Urano foi visto antes de 1781, mas confundido com:", choices: ["Estrela", "Cometa", "Asteroide", "Lua"], answer: 0 },
    { level: 3, q: "Urano aparece como personagem em qual mito grego?", choices: ["Pai do céu (Ouranos)", "Deus do mar", "Deus do trovão", "Deus do fogo"], answer: 0 },
  ],
  netuno: [
    { level: 1, q: "Netuno é conhecido pela cor:", choices: ["Vermelha", "Azul intensa", "Amarela", "Branca"], answer: 1 },
    { level: 1, q: "Netuno é o planeta mais distante do Sol?", choices: ["Sim", "Não, Plutão é", "Não, Marte é", "Não, Mercúrio é"], answer: 0 },
    { level: 1, q: "Netuno recebeu nome do deus romano de:", choices: ["Guerra", "Mar", "Sol", "Amor"], answer: 1 },
    { level: 1, q: "Netuno tem ventos:", choices: ["Inexistentes", "Os mais rápidos do Sistema Solar", "Quentes", "De vapor"], answer: 1 },
    { level: 1, q: "Netuno é um planeta:", choices: ["Gigante gelado", "Rochoso", "Estrela", "Anão"], answer: 0 },
    { level: 1, q: "Netuno é maior ou menor que a Terra?", choices: ["Maior", "Menor", "Igual", "Igual à Lua"], answer: 0 },
    { level: 1, q: "Netuno é visível a olho nu?", choices: ["Não, só com telescópio", "Sim, brilhante", "Sim, de dia", "Sim, ao lado da Lua"], answer: 0 },
    { level: 1, q: "Netuno fica antes ou depois de Urano?", choices: ["Depois", "Antes", "Mesma órbita", "Dentro de Urano"], answer: 0 },
    { level: 1, q: "Netuno tem anéis?", choices: ["Sim, finos", "Não", "Sim, gigantes", "Sim, de fogo"], answer: 0 },
    { level: 1, q: "Netuno é o ___ planeta a partir do Sol.", choices: ["6º", "7º", "8º", "9º"], answer: 2 },
    { level: 2, q: "Qual destas é uma lua de Netuno?", choices: ["Tritão", "Titã", "Europa", "Fobos"], answer: 0 },
    { level: 2, q: "Tritão é especial porque orbita Netuno:", choices: ["Em sentido retrógrado", "Sem se mover", "Em zigue-zague", "Em queda livre"], answer: 0 },
    { level: 2, q: "Netuno completa um ano em quanto tempo?", choices: ["~165 anos terrestres", "1 ano", "10 anos", "1 mês"], answer: 0 },
    { level: 2, q: "A cor azul intensa de Netuno vem do:", choices: ["Metano", "Oxigênio", "Hidrogênio", "Hélio"], answer: 0 },
    { level: 2, q: "Netuno foi descoberto por cálculos matemáticos no século:", choices: ["XVII", "XVIII", "XIX", "XX"], answer: 2 },
    { level: 2, q: "Netuno tem uma tempestade que já foi chamada:", choices: ["Grande Mancha Escura", "Mancha Vermelha", "Olho do Furacão", "Buraco Branco"], answer: 0 },
    { level: 2, q: "Os ventos de Netuno passam de:", choices: ["2000 km/h", "100 km/h", "10 km/h", "0 km/h"], answer: 0 },
    { level: 2, q: "Netuno faz parte do grupo de planetas:", choices: ["Gigantes gelados", "Rochosos", "Anões", "Estrelas"], answer: 0 },
    { level: 2, q: "Netuno foi descoberto em:", choices: ["1846", "1781", "1900", "1957"], answer: 0 },
    { level: 2, q: "Tritão pode ter origem em qual região?", choices: ["Cinturão de Kuiper (capturada)", "Sol", "Sistema de Júpiter", "Terra"], answer: 0 },
    { level: 3, q: "Qual única sonda passou por Netuno (1989)?", choices: ["Voyager 2", "Voyager 1", "Cassini", "Juno"], answer: 0 },
    { level: 3, q: "Quem previu matematicamente Netuno antes da descoberta?", choices: ["Le Verrier e Adams", "Galileu", "Newton sozinho", "Einstein"], answer: 0 },
    { level: 3, q: "Quem observou Netuno pela 1ª vez no telescópio?", choices: ["Johann Galle", "Galileu", "Herschel", "Hubble"], answer: 0 },
    { level: 3, q: "Tritão é maior ou menor que a Lua da Terra?", choices: ["Um pouco menor", "Muito maior", "Igual", "Tamanho de Júpiter"], answer: 0 },
    { level: 3, q: "Netuno tem campo magnético inclinado em relação ao eixo?", choices: ["Sim, fortemente inclinado", "Não", "Igual ao eixo", "Não tem campo"], answer: 0 },
    { level: 3, q: "Quanto dura 1 dia em Netuno?", choices: ["~16 horas", "24 horas", "1 semana", "1 mês"], answer: 0 },
    { level: 3, q: "Em mitologia, Netuno corresponde a qual deus grego?", choices: ["Poseidon", "Zeus", "Hades", "Ares"], answer: 0 },
    { level: 3, q: "Tritão tem géiseres de:", choices: ["Nitrogênio", "Lava", "Água quente", "Petróleo"], answer: 0 },
    { level: 3, q: "Netuno também é classificado como:", choices: ["Gigante gelado", "Gigante gasoso quente", "Anão", "Estrela jovem"], answer: 0 },
    { level: 3, q: "Galileu chegou a observar Netuno mas pensou que era:", choices: ["Estrela", "Cometa", "Asteroide", "Lua"], answer: 0 },
  ],
  plutao: [
    { level: 1, q: "Plutão é hoje classificado como:", choices: ["Planeta", "Lua", "Planeta anão", "Cometa"], answer: 2 },
    { level: 1, q: "Em que ano Plutão perdeu o status de planeta principal?", choices: ["1995", "2006", "2015", "2020"], answer: 1 },
    { level: 1, q: "Plutão é maior ou menor que a Lua?", choices: ["Maior", "Menor", "Igual", "Tamanho da Terra"], answer: 1 },
    { level: 1, q: "Plutão é frio?", choices: ["Sim, extremamente", "Não, é quente", "Médio", "Tropical"], answer: 0 },
    { level: 1, q: "Plutão recebeu nome do deus romano do:", choices: ["Mundo dos mortos", "Trovão", "Mar", "Sol"], answer: 0 },
    { level: 1, q: "Plutão tem atmosfera?", choices: ["Sim, fina", "Não tem nada", "Densa como a da Terra", "Só de oxigênio"], answer: 0 },
    { level: 1, q: "Plutão é mais perto ou mais longe do Sol que Netuno?", choices: ["Sempre mais perto", "Em geral mais longe", "Mesma distância", "Está dentro do Sol"], answer: 1 },
    { level: 1, q: "Plutão é visível a olho nu?", choices: ["Não, precisa de telescópio", "Sim", "Só de dia", "Só na Lua cheia"], answer: 0 },
    { level: 1, q: "Plutão fica em qual região externa?", choices: ["Cinturão de Kuiper", "Cinturão de asteroides", "Anel de Saturno", "Marte"], answer: 0 },
    { level: 1, q: "Plutão é mais escuro ou claro que a Lua?", choices: ["Mais escuro", "Mais claro", "Igual", "Brilha"], answer: 0 },
    { level: 2, q: "Qual a maior lua de Plutão?", choices: ["Caronte", "Europa", "Titã", "Lua"], answer: 0 },
    { level: 2, q: "Qual sonda da NASA visitou Plutão em 2015?", choices: ["Voyager 1", "New Horizons", "Cassini", "Juno"], answer: 1 },
    { level: 2, q: "Plutão foi descoberto em:", choices: ["1930", "1781", "1846", "2000"], answer: 0 },
    { level: 2, q: "Quem descobriu Plutão?", choices: ["Clyde Tombaugh", "Galileu", "Einstein", "Hubble"], answer: 0 },
    { level: 2, q: "Plutão leva quantos anos para 1 volta no Sol?", choices: ["~248 anos", "1 ano", "10 anos", "1000 anos"], answer: 0 },
    { level: 2, q: "O coração visível em Plutão se chama:", choices: ["Tombaugh Regio", "Olympus", "Maxwell", "Hellas"], answer: 0 },
    { level: 2, q: "Plutão e Caronte são considerados sistema:", choices: ["Binário", "Solo", "Triplo", "Sem orbita"], answer: 0 },
    { level: 2, q: "Plutão foi rebaixado por decisão de qual organização?", choices: ["UAI (IAU)", "NASA", "ONU", "ESA"], answer: 0 },
    { level: 2, q: "Plutão recebeu nome sugerido por uma criança chamada:", choices: ["Venetia Burney", "Marie Curie", "Ada Lovelace", "Greta"], answer: 0 },
    { level: 2, q: "Plutão é mais ou menos massivo que a Lua da Terra?", choices: ["Menos massivo", "Mais massivo", "Igual", "Igual à Terra"], answer: 0 },
    { level: 3, q: "Quantas luas Plutão tem?", choices: ["5", "1", "0", "20"], answer: 0 },
    { level: 3, q: "Cite uma lua de Plutão além de Caronte:", choices: ["Hidra ou Nix", "Lua", "Titã", "Europa"], answer: 0 },
    { level: 3, q: "A New Horizons foi lançada em:", choices: ["2006", "1996", "2015", "2020"], answer: 0 },
    { level: 3, q: "A New Horizons fez sobrevoo de Plutão em qual data?", choices: ["14/jul/2015", "1/jan/2000", "10/dez/2020", "25/dez/1995"], answer: 0 },
    { level: 3, q: "Plutão tem montanhas de:", choices: ["Gelo (água)", "Granito", "Ouro", "Lava"], answer: 0 },
    { level: 3, q: "Plutão e Caronte mostram travamento:", choices: ["Gravitacional mútuo (mostram sempre mesma face)", "Magnético", "Solar", "Quântico"], answer: 0 },
    { level: 3, q: "O cinturão de Kuiper foi proposto por:", choices: ["Gerard Kuiper", "Einstein", "Hubble", "Sagan"], answer: 0 },
    { level: 3, q: "A temperatura média de Plutão fica em torno de:", choices: ["-230 °C", "0 °C", "100 °C", "-50 °C"], answer: 0 },
    { level: 3, q: "Plutão é considerado o ___ entre os planetas anões conhecidos.", choices: ["Maior do cinturão de Kuiper conhecido", "Menor de todos", "Mais quente", "Mais brilhante"], answer: 0 },
    { level: 3, q: "Plutão chegou a estar mais perto do Sol que Netuno entre:", choices: ["1979 e 1999", "1900 e 1910", "2010 e 2020", "Nunca"], answer: 0 },
  ],
  kepler: [
    { level: 1, q: "Kepler-22b é:", choices: ["Uma lua", "Um exoplaneta", "Uma galáxia", "Um cometa"], answer: 1 },
    { level: 1, q: "Exoplanetas são planetas que orbitam:", choices: ["O nosso Sol", "Outras estrelas", "A Lua", "Buracos negros apenas"], answer: 1 },
    { level: 1, q: "Kepler-22b ficou famoso porque pode ter:", choices: ["Vulcões ativos", "Água líquida", "Anéis", "Vida confirmada"], answer: 1 },
    { level: 1, q: "Kepler-22b está em qual zona da sua estrela?", choices: ["Zona morta", "Zona habitável", "Zona de gelo", "Dentro da estrela"], answer: 1 },
    { level: 1, q: "Kepler-22b está dentro do Sistema Solar?", choices: ["Sim", "Não", "Só metade", "Em órbita da Lua"], answer: 1 },
    { level: 1, q: "Kepler-22b foi anunciado pela NASA em:", choices: ["2011", "1999", "2020", "1980"], answer: 0 },
    { level: 1, q: "Telescópio Kepler pertence a qual agência?", choices: ["NASA", "ESA", "Roscosmos", "JAXA"], answer: 0 },
    { level: 1, q: "Kepler-22b é maior ou menor que a Terra?", choices: ["Maior", "Igual", "Menor", "Tamanho da Lua"], answer: 0 },
    { level: 1, q: "Kepler-22b foi descoberto por qual telescópio?", choices: ["Hubble", "Kepler", "James Webb", "Galileo"], answer: 1 },
    { level: 1, q: "Estudar exoplanetas ajuda a procurar:", choices: ["Petróleo", "Vida fora da Terra", "Ouro", "Plástico"], answer: 1 },
    { level: 2, q: "Kepler-22b fica a quantos anos-luz da Terra (aprox.)?", choices: ["~600", "1", "1 milhão", "10"], answer: 0 },
    { level: 2, q: "Kepler-22b leva quantos dias para 1 volta na sua estrela?", choices: ["~290 dias", "1 dia", "1000 anos", "1 hora"], answer: 0 },
    { level: 2, q: "A estrela de Kepler-22b é parecida com:", choices: ["O Sol (tipo G)", "Buraco negro", "Anã marrom", "Estrela de nêutrons"], answer: 0 },
    { level: 2, q: "O telescópio Kepler foi lançado em:", choices: ["2009", "1999", "2018", "2020"], answer: 0 },
    { level: 2, q: "O método principal do Kepler para achar exoplanetas é:", choices: ["Trânsito", "Olho nu", "Som", "Calor"], answer: 0 },
    { level: 2, q: "Quantos exoplanetas já foram confirmados (>5000)?", choices: ["Mais de 5000", "10", "100", "1"], answer: 0 },
    { level: 2, q: "Kepler-22b está na constelação de:", choices: ["Cisne", "Órion", "Cruzeiro", "Touro"], answer: 0 },
    { level: 2, q: "James Webb estuda exoplanetas com qual luz?", choices: ["Infravermelho", "Som", "Raios-X apenas", "Microondas apenas"], answer: 0 },
    { level: 2, q: "Kepler-22b foi o primeiro do telescópio na ___ habitável.", choices: ["Zona habitável de uma estrela tipo solar", "Zona morta", "Centro da galáxia", "Lua"], answer: 0 },
    { level: 2, q: "Para ter água líquida, o planeta precisa estar na zona:", choices: ["Habitável (de Goldilocks)", "De Kuiper", "De Oort", "Solar fria"], answer: 0 },
    { level: 3, q: "O nome Kepler homenageia:", choices: ["Johannes Kepler", "Einstein", "Newton", "Galileu"], answer: 0 },
    { level: 3, q: "A missão Kepler foi aposentada em:", choices: ["2018", "2000", "2020", "1990"], answer: 0 },
    { level: 3, q: "Kepler-22b tem raio aproximadamente:", choices: ["~2,4× o da Terra", "Igual à Terra", "10× o do Sol", "Igual à Lua"], answer: 0 },
    { level: 3, q: "Quem sucedeu Kepler na caça de exoplanetas?", choices: ["TESS", "Voyager 3", "Cassini 2", "Pioneer 12"], answer: 0 },
    { level: 3, q: "Quando foi descoberto o 1º exoplaneta confirmado em estrela solar?", choices: ["1995 (51 Pegasi b)", "1500", "2010", "2020"], answer: 0 },
    { level: 3, q: "Quem descobriu 51 Pegasi b (Nobel 2019)?", choices: ["Mayor e Queloz", "Einstein", "Hawking", "Hubble"], answer: 0 },
    { level: 3, q: "Trânsito planetário é quando o planeta:", choices: ["Passa na frente da estrela", "Bate na estrela", "Some no buraco negro", "Para de girar"], answer: 0 },
    { level: 3, q: "Kepler-22b ainda não teve atmosfera detectada?", choices: ["Correto", "Já tem vida confirmada", "Tem oceano filmado", "Tem cidades"], answer: 0 },
    { level: 3, q: "Quantos planetas o Kepler confirmou aproximadamente?", choices: ["Mais de 2500", "5", "10", "100000"], answer: 0 },
    { level: 3, q: "O conceito de zona habitável também é chamado:", choices: ["Zona de Cachinhos Dourados", "Zona Roxa", "Zona Negra", "Zona Branca"], answer: 0 },
  ],
  proxima: [
    { level: 1, q: "Proxima Centauri é a estrela mais ___ do Sol.", choices: ["Brilhante", "Próxima", "Distante", "Antiga"], answer: 1 },
    { level: 1, q: "Proxima Centauri b é um:", choices: ["Cometa", "Exoplaneta", "Satélite artificial", "Buraco negro"], answer: 1 },
    { level: 1, q: "Quantos anos-luz a Proxima Centauri está da Terra (aprox.)?", choices: ["4", "100", "1.000", "1 milhão"], answer: 0 },
    { level: 1, q: "Proxima Centauri b está na zona:", choices: ["Habitável", "Morta", "De Kuiper", "Galáctica"], answer: 0 },
    { level: 1, q: "Proxima Centauri pertence ao sistema:", choices: ["Alpha Centauri", "Andrômeda", "Via Láctea isolada", "Plutão"], answer: 0 },
    { level: 1, q: "Em Star Wars, qual a velocidade usada para grandes distâncias?", choices: ["Do som", "Hiperespaço (velocidade da luz)", "Do vento", "Andando"], answer: 1 },
    { level: 1, q: "Buraco de minhoca é conceito popularizado em qual filme?", choices: ["Titanic", "Interestelar", "Rocky", "Frozen"], answer: 1 },
    { level: 1, q: "Proxima Centauri é visível principalmente em qual hemisfério?", choices: ["Sul", "Norte", "Nenhum", "Marte"], answer: 0 },
    { level: 1, q: "Proxima Centauri é uma estrela:", choices: ["Anã vermelha", "Gigante azul", "Sol nascente", "Buraco negro"], answer: 0 },
    { level: 1, q: "Próxima Centauri b é mais parecido em massa com:", choices: ["Terra", "Júpiter", "Sol", "Lua"], answer: 0 },
    { level: 2, q: "Proxima Centauri b leva ~ quantos dias para 1 órbita?", choices: ["~11 dias", "1 ano", "100 anos", "1 mês"], answer: 0 },
    { level: 2, q: "O sistema Alpha Centauri tem quantas estrelas principais?", choices: ["1", "2", "3", "10"], answer: 2 },
    { level: 2, q: "Proxima Centauri b foi anunciado em:", choices: ["2016", "1999", "2022", "1980"], answer: 0 },
    { level: 2, q: "Anãs vermelhas têm tempo de vida:", choices: ["Muito longo", "Muito curto", "Igual ao Sol", "1 ano"], answer: 0 },
    { level: 2, q: "Proxima b sofre forte:", choices: ["Radiação de flares da estrela", "Pressão do Sol da Terra", "Vento de Júpiter", "Marés da Lua"], answer: 0 },
    { level: 2, q: "Distância em km da Proxima Centauri é da ordem de:", choices: ["~40 trilhões de km", "100 km", "1 milhão km", "10 km"], answer: 0 },
    { level: 2, q: "Sondas atuais levariam ~ quanto tempo até Proxima Centauri?", choices: ["Dezenas de milhares de anos", "1 ano", "1 semana", "1 dia"], answer: 0 },
    { level: 2, q: "Projeto Breakthrough Starshot quer chegar lá com:", choices: ["Velas leves a laser", "Foguete químico", "Trem", "Submarino"], answer: 0 },
    { level: 2, q: "Proxima Centauri provavelmente forma sistema ___ com Alpha Cen AB.", choices: ["Triplo", "Solo", "Quádruplo", "Sem ligação"], answer: 0 },
    { level: 2, q: "Em Avatar (Cameron), Pandora orbita uma estrela do sistema:", choices: ["Alpha Centauri (ficção)", "Sol", "Sirius", "Andrômeda"], answer: 0 },
    { level: 3, q: "Proxima Centauri foi descoberta em:", choices: ["1915", "1500", "1990", "2010"], answer: 0 },
    { level: 3, q: "Quem descobriu Proxima Centauri?", choices: ["Robert Innes", "Galileu", "Newton", "Hubble"], answer: 0 },
    { level: 3, q: "O nome 'Proxima' significa, em latim:", choices: ["Mais próxima", "Mais distante", "Mais brilhante", "Mais antiga"], answer: 0 },
    { level: 3, q: "A classe estelar de Proxima é:", choices: ["M (anã vermelha)", "G (como o Sol)", "O (gigante azul)", "A (branca)"], answer: 0 },
    { level: 3, q: "Proxima Centauri tem quantos planetas conhecidos?", choices: ["Pelo menos 2 (b e d) + candidatos", "0", "10", "1000"], answer: 0 },
    { level: 3, q: "Distância em parsecs entre Sol e Proxima é cerca de:", choices: ["~1,3 pc", "100 pc", "0,01 pc", "1000 pc"], answer: 0 },
    { level: 3, q: "Proxima Centauri b foi confirmada por método de:", choices: ["Velocidade radial", "Foto direta única", "Pouso", "Som"], answer: 0 },
    { level: 3, q: "O nome Alpha Centauri se refere ao:", choices: ["Astro mais brilhante de Centaurus", "Mais escuro", "Sol da Terra", "Centro da galáxia"], answer: 0 },
    { level: 3, q: "Anãs vermelhas como Proxima são as estrelas mais ___ da galáxia.", choices: ["Comuns", "Raras", "Quentes", "Antigas únicas"], answer: 0 },
    { level: 3, q: "Distância da Proxima até Alpha Cen AB é cerca de:", choices: ["0,2 anos-luz", "1000 anos-luz", "0 (são iguais)", "1 milhão anos-luz"], answer: 0 },
  ],
  sol: [
    { level: 1, q: "O Sol é classificado como:", choices: ["Planeta", "Lua", "Estrela", "Cometa"], answer: 2 },
    { level: 1, q: "De que cor o Sol é representado?", choices: ["Amarelo", "Verde", "Preto", "Rosa"], answer: 0 },
    { level: 1, q: "O Sol está no centro de qual sistema?", choices: ["Sistema Solar", "Andrômeda", "Buraco Negro", "Sistema da Lua"], answer: 0 },
    { level: 1, q: "Olhar diretamente para o Sol faz mal aos olhos?", choices: ["Sim, muito", "Não, é seguro", "Só de manhã", "Só com lupa"], answer: 0 },
    { level: 1, q: "O Sol nasce em qual ponto cardeal (aprox.)?", choices: ["Leste", "Oeste", "Norte", "Sul"], answer: 0 },
    { level: 1, q: "Sem o Sol, a Terra ficaria:", choices: ["Fria e sem vida", "Quente", "Verde", "Igual"], answer: 0 },
    { level: 1, q: "O Sol é maior que a Terra?", choices: ["Muito maior", "Menor", "Igual", "Igual à Lua"], answer: 0 },
    { level: 1, q: "Eclipse solar é quando ___ tampa o Sol.", choices: ["A Lua", "Marte", "Júpiter", "Saturno"], answer: 0 },
    { level: 1, q: "O Sol gira em torno de si mesmo?", choices: ["Sim", "Não", "Só de noite", "Só em dia bissexto"], answer: 0 },
    { level: 1, q: "A luz do Sol é fonte de qual vitamina pelo nosso corpo?", choices: ["D", "A", "B12", "C"], answer: 0 },
    { level: 2, q: "Quanto tempo a luz do Sol leva pra chegar à Terra?", choices: ["8 segundos", "8 minutos", "8 horas", "8 dias"], answer: 1 },
    { level: 2, q: "A energia do Sol vem de qual processo?", choices: ["Combustão", "Fusão nuclear", "Eletricidade", "Atrito"], answer: 1 },
    { level: 2, q: "O Sol é feito principalmente de:", choices: ["Pedra", "Hidrogênio e hélio", "Água", "Ferro"], answer: 1 },
    { level: 2, q: "A camada visível do Sol se chama:", choices: ["Fotosfera", "Crosta", "Manto", "Núcleo externo"], answer: 0 },
    { level: 2, q: "Manchas solares são regiões mais:", choices: ["Frias e magnéticas", "Quentes que o normal", "Vazias", "Sem gravidade"], answer: 0 },
    { level: 2, q: "O Sol pertence a qual galáxia?", choices: ["Via Láctea", "Andrômeda", "Triângulo", "Sombrero"], answer: 0 },
    { level: 2, q: "Sol é uma estrela do tipo (classe):", choices: ["G", "M", "O", "B"], answer: 0 },
    { level: 2, q: "O Sol tem cerca de quantos anos?", choices: ["~4,6 bilhões", "100 milhões", "1 milhão", "5 mil"], answer: 0 },
    { level: 2, q: "A coroa solar é vista melhor durante:", choices: ["Eclipse total", "Dia comum", "Noite", "Chuva"], answer: 0 },
    { level: 2, q: "Vento solar é fluxo de:", choices: ["Partículas carregadas", "Ar", "Água", "Som"], answer: 0 },
    { level: 3, q: "A temperatura na superfície do Sol é aproximadamente:", choices: ["~5500 °C", "100 °C", "1 milhão °C", "30 °C"], answer: 0 },
    { level: 3, q: "A temperatura no núcleo do Sol é da ordem de:", choices: ["~15 milhões °C", "1000 °C", "100 °C", "1 bilhão °C"], answer: 0 },
    { level: 3, q: "Qual sonda da NASA chegou mais perto do Sol até hoje?", choices: ["Parker Solar Probe", "Voyager 1", "Cassini", "Hubble"], answer: 0 },
    { level: 3, q: "A missão Solar Orbiter é da:", choices: ["ESA/NASA", "Roscosmos", "ISRO", "JAXA sozinha"], answer: 0 },
    { level: 3, q: "Em ~5 bilhões de anos o Sol virará:", choices: ["Gigante vermelha e depois anã branca", "Buraco negro gigante", "Anã marrom", "Estrela de nêutrons"], answer: 0 },
    { level: 3, q: "Auroras na Terra são causadas principalmente por:", choices: ["Vento solar + campo magnético da Terra", "Chuva", "Vulcões", "Avião"], answer: 0 },
    { level: 3, q: "A camada do Sol entre fotosfera e coroa se chama:", choices: ["Cromosfera", "Astenosfera", "Crosta", "Manto"], answer: 0 },
    { level: 3, q: "O ciclo magnético do Sol dura cerca de:", choices: ["11 anos", "1 ano", "100 anos", "1 dia"], answer: 0 },
    { level: 3, q: "Distância média Sol–Terra é chamada de 1:", choices: ["UA (unidade astronômica)", "Ano-luz", "Parsec", "Km solar"], answer: 0 },
    { level: 3, q: "1 UA equivale a aproximadamente:", choices: ["~150 milhões de km", "1 milhão km", "1 bilhão km", "100 km"], answer: 0 },
  ],
  alpha_a: [
    { level: 1, q: "Alpha Centauri A está em qual constelação?", choices: ["Centauro", "Órion", "Cruzeiro do Sul", "Pégaso"], answer: 0 },
    { level: 1, q: "Alpha Centauri A é parecida com qual estrela?", choices: ["Sol", "Sirius", "Betelgeuse", "Lua"], answer: 0 },
    { level: 1, q: "Alpha Centauri é visível principalmente em qual hemisfério?", choices: ["Norte", "Sul", "Nenhum", "Marte"], answer: 1 },
    { level: 1, q: "Alpha Centauri A é a estrela mais ___ do seu sistema.", choices: ["Pequena", "Brilhante", "Fria", "Antiga"], answer: 1 },
    { level: 1, q: "Alpha Centauri é um sistema de quantas estrelas?", choices: ["1", "2", "3", "10"], answer: 2 },
    { level: 1, q: "Velas solares são impulsionadas por:", choices: ["Combustível líquido", "Luz/radiação das estrelas", "Vento comum", "Eletricidade"], answer: 1 },
    { level: 1, q: "Sistemas estelares múltiplos têm:", choices: ["1 estrela", "Várias estrelas orbitando entre si", "Só planetas", "Só luas"], answer: 1 },
    { level: 1, q: "Alpha Centauri pode ser vista a olho nu?", choices: ["Sim, é brilhante", "Não", "Só de dia", "Só de avião"], answer: 0 },
    { level: 1, q: "Alpha Centauri A faz parte do grupo de estrelas mais ___ ao Sol.", choices: ["Próximas", "Distantes", "Pequenas", "Quentes"], answer: 0 },
    { level: 1, q: "Alpha Centauri AB e Proxima formam sistema ___.", choices: ["Triplo", "Único", "Quádruplo", "Sem ligação"], answer: 0 },
    { level: 2, q: "Distância (aprox.) de Alpha Centauri A ao Sol:", choices: ["~4,3 anos-luz", "100 anos-luz", "1 ano-luz", "1.000 anos-luz"], answer: 0 },
    { level: 2, q: "A classe estelar de Alpha Centauri A é:", choices: ["G2V (como o Sol)", "M", "O", "B"], answer: 0 },
    { level: 2, q: "Alpha Centauri A e B orbitam entre si em ~ quantos anos?", choices: ["~80 anos", "1 ano", "1 milhão", "1 dia"], answer: 0 },
    { level: 2, q: "Alpha Centauri é o ___ astro mais brilhante do céu noturno.", choices: ["3º", "1º", "100º", "Último"], answer: 0 },
    { level: 2, q: "Alpha Centauri AB também é chamada de:", choices: ["Rigil Kentaurus", "Sirius", "Vega", "Betelgeuse"], answer: 0 },
    { level: 2, q: "A constelação do Centauro aparece em céus de qual região?", choices: ["Hemisfério sul (Brasil)", "Hemisfério norte ártico", "Polo Norte", "Marte"], answer: 0 },
    { level: 2, q: "Alpha Cen B é classe:", choices: ["K (laranja)", "M (vermelha)", "O (azul)", "F (branca)"], answer: 0 },
    { level: 2, q: "Em ficção, Avatar de Cameron se passa em volta de:", choices: ["Alpha Centauri", "Sol", "Andrômeda", "Sirius"], answer: 0 },
    { level: 2, q: "O Breakthrough Starshot tem como alvo principal:", choices: ["Sistema Alpha Centauri", "Marte", "Lua", "Plutão"], answer: 0 },
    { level: 2, q: "Alpha Centauri é, em distância, depois do Sol, a ___ estrela conhecida.", choices: ["Mais próxima do Sol (sistema)", "Mais distante", "Mais escura", "Mais densa"], answer: 0 },
    { level: 3, q: "Quem identificou Alpha Centauri como sistema múltiplo?", choices: ["Father Richaud / John Herschel (sec. XVII–XIX)", "Galileu sozinho", "Einstein", "Hubble"], answer: 0 },
    { level: 3, q: "Alpha Cen A é mais massiva ou menos que o Sol?", choices: ["Pouco mais massiva", "Muito menor", "Igual à Lua", "Igual a Júpiter"], answer: 0 },
    { level: 3, q: "Tipo espectral exato do Sol é:", choices: ["G2V", "M5V", "O3", "K7"], answer: 0 },
    { level: 3, q: "A separação média entre Alpha Cen A e B é da ordem de:", choices: ["~23 UA", "1 UA", "1000 UA", "0 UA"], answer: 0 },
    { level: 3, q: "Alpha Centauri tem planeta confirmado em qual componente?", choices: ["Proxima (Cen C)", "Alpha A apenas", "Alpha B apenas", "Nenhum até hoje"], answer: 0 },
    { level: 3, q: "Distância de Alpha Centauri ao Sol em parsecs (aprox.):", choices: ["~1,3 pc", "100 pc", "0,01 pc", "1000 pc"], answer: 0 },
    { level: 3, q: "Em Star Trek (universo expandido), Alpha Centauri é base de:", choices: ["Zefram Cochrane (ficção)", "Darth Vader", "Yoda", "Spock-rey"], answer: 0 },
    { level: 3, q: "O Sol viaja pela galáxia a aproximadamente:", choices: ["~220 km/s", "1 km/s", "1000 km/s", "Estático"], answer: 0 },
    { level: 3, q: "Alpha Centauri AB se afastará ou se aproximará do Sol?", choices: ["Se aproxima hoje, depois afasta", "Sempre afasta", "Sempre fica igual", "Está parada"], answer: 0 },
    { level: 3, q: "Alpha Centauri é a estrela alfa da constelação:", choices: ["Centauro", "Cruzeiro do Sul", "Órion", "Touro"], answer: 0 },
  ],
  betelgeuse: [
    { level: 1, q: "Betelgeuse fica na constelação de:", choices: ["Órion", "Centauro", "Cruzeiro", "Touro"], answer: 0 },
    { level: 1, q: "Betelgeuse é uma estrela:", choices: ["Anã branca", "Supergigante vermelha", "De nêutrons", "Anã amarela"], answer: 1 },
    { level: 1, q: "Betelgeuse pode ser vista a olho nu?", choices: ["Sim, é brilhante", "Não", "Só com Hubble", "Só de manhã"], answer: 0 },
    { level: 1, q: "Qual filme de Tim Burton tem 'Beetlejuice' no nome?", choices: ["Edward Mãos de Tesoura", "Os Fantasmas se Divertem", "Batman", "Frankenweenie"], answer: 1 },
    { level: 1, q: "Órion é famosa pelas suas:", choices: ["3 estrelas em linha (Três Marias)", "Anéis", "Luas", "Crateras"], answer: 0 },
    { level: 1, q: "Betelgeuse é uma das estrelas mais ___ visíveis no céu noturno.", choices: ["Apagadas", "Brilhantes", "Escondidas", "Pequenas"], answer: 1 },
    { level: 1, q: "Betelgeuse é candidata a explodir como:", choices: ["Buraco negro pequeno", "Supernova", "Cometa", "Asteroide"], answer: 1 },
    { level: 1, q: "Betelgeuse é maior ou menor que o Sol?", choices: ["Gigantescamente maior", "Menor", "Igual", "Igual à Lua"], answer: 0 },
    { level: 1, q: "A cor de Betelgeuse é:", choices: ["Vermelho-alaranjada", "Azul", "Branca", "Verde"], answer: 0 },
    { level: 1, q: "Órion lembra a figura de um:", choices: ["Caçador", "Pato", "Cachorro", "Carro"], answer: 0 },
    { level: 2, q: "Betelgeuse fica a quantos anos-luz da Terra (aprox.)?", choices: ["~640", "10", "1 milhão", "1"], answer: 0 },
    { level: 2, q: "Em 2019/2020 Betelgeuse ficou famosa porque:", choices: ["Diminuiu de brilho de forma incomum", "Explodiu", "Desapareceu", "Mudou de cor para verde"], answer: 0 },
    { level: 2, q: "Se Betelgeuse virar supernova, será visível:", choices: ["Da Terra, de dia inclusive", "Só com Hubble", "Nunca", "Só de Marte"], answer: 0 },
    { level: 2, q: "Betelgeuse, em árabe, significa algo como:", choices: ["Ombro/mão do gigante", "Pé do urso", "Olho do dragão", "Cabeça do lobo"], answer: 0 },
    { level: 2, q: "Se Betelgeuse estivesse no lugar do Sol, engoliria até:", choices: ["A órbita de Júpiter", "Só Mercúrio", "Só a Lua", "Nada"], answer: 0 },
    { level: 2, q: "A massa de Betelgeuse é várias vezes a do Sol?", choices: ["Sim, ~10–20×", "Não, é menor", "Igual ao Sol", "Igual à Terra"], answer: 0 },
    { level: 2, q: "Betelgeuse é uma estrela ___ (idade).", choices: ["Jovem em escala estelar", "Muito velha (bilhões de anos)", "Tem 10 anos", "Recém-formada esta semana"], answer: 0 },
    { level: 2, q: "Órion contém o famoso/conhecido Cinturão (3 estrelas) e:", choices: ["Nebulosa de Órion", "Cinturão de Kuiper", "Anel de Saturno", "Andrômeda"], answer: 0 },
    { level: 2, q: "Outra supergigante azul de Órion é:", choices: ["Rigel", "Vega", "Sirius", "Polaris"], answer: 0 },
    { level: 2, q: "A Nebulosa de Órion é berçário de:", choices: ["Estrelas", "Cometas", "Buracos negros prontos", "Planetas anões"], answer: 0 },
    { level: 3, q: "Betelgeuse é classificada como tipo espectral:", choices: ["M (vermelha)", "G (amarela)", "O (azul)", "F (branca)"], answer: 0 },
    { level: 3, q: "Betelgeuse pulsa de brilho com período de:", choices: ["~400 dias", "1 dia", "100 anos", "1 hora"], answer: 0 },
    { level: 3, q: "O 'dimming' de Betelgeuse em 2019–2020 foi causado em parte por:", choices: ["Nuvem de poeira ejetada", "Eclipse de planeta", "Lua tapando", "Avião"], answer: 0 },
    { level: 3, q: "Betelgeuse provavelmente virará supernova em até:", choices: ["~100 mil anos", "10 segundos", "1 ano garantido", "1 bilhão de anos exatos"], answer: 0 },
    { level: 3, q: "A nomenclatura Bayer de Betelgeuse é:", choices: ["α Orionis", "β Orionis", "γ Orionis", "δ Orionis"], answer: 0 },
    { level: 3, q: "A primeira imagem direta da superfície de outra estrela foi de:", choices: ["Betelgeuse", "Sol", "Sirius", "Rigel"], answer: 0 },
    { level: 3, q: "Quem fez essa primeira imagem (Hubble, ~1995)?", choices: ["NASA/ESA via Hubble", "Galileu", "Voyager", "ESA pisando lá"], answer: 0 },
    { level: 3, q: "Beetlejuice (filme de 1988) é dirigido por:", choices: ["Tim Burton", "Spielberg", "Cameron", "Nolan"], answer: 0 },
    { level: 3, q: "Em mitologia grega, Órion era um:", choices: ["Caçador gigante", "Faraó", "Mago", "Pescador"], answer: 0 },
    { level: 3, q: "Betelgeuse é classificada como supergigante:", choices: ["Vermelha tipo M", "Branca tipo F", "Anã amarela tipo G", "Azul tipo B"], answer: 0 },
  ],
  lua: [
    { level: 1, q: "Qual satélite natural orbita a Terra?", choices: ["Europa", "Lua", "Titã", "Fobos"], answer: 1 },
    { level: 1, q: "Em que ano o homem pisou na Lua pela 1ª vez?", choices: ["1959", "1969", "1979", "1989"], answer: 1 },
    { level: 1, q: "Qual astronauta deu o 1º passo na Lua?", choices: ["Yuri Gagarin", "Neil Armstrong", "Buzz Aldrin", "Elon Musk"], answer: 1 },
    { level: 1, q: "A Lua influencia diretamente o que na Terra?", choices: ["Cor do céu", "Marés", "Vento solar", "Eclipses do Sol apenas"], answer: 1 },
    { level: 1, q: "A Lua é maior ou menor que a Terra?", choices: ["Maior", "Igual", "Menor", "Tamanho do Sol"], answer: 2 },
    { level: 1, q: "Qual o nome da missão que levou o homem à Lua em 1969?", choices: ["Apollo 11", "Soyuz", "Gemini", "Mercury"], answer: 0 },
    { level: 1, q: "A Lua tem fases?", choices: ["Sim (cheia, nova, etc.)", "Não", "Só uma", "Só de dia"], answer: 0 },
    { level: 1, q: "A Lua brilha porque:", choices: ["Reflete a luz do Sol", "Faz fusão como o Sol", "Tem energia elétrica", "Tem fogo"], answer: 0 },
    { level: 1, q: "A Lua é o ___ corpo mais brilhante visto da Terra.", choices: ["1º (depois do Sol)", "Último", "Igual a Marte", "Nem aparece"], answer: 0 },
    { level: 1, q: "Eclipse lunar é quando ___ tampa a Lua.", choices: ["A sombra da Terra", "Mercúrio", "Vênus", "Júpiter"], answer: 0 },
    { level: 2, q: "Quanto tempo a Lua leva para dar 1 volta na Terra?", choices: ["~27,3 dias", "1 dia", "1 ano", "1 semana"], answer: 0 },
    { level: 2, q: "A Lua tem atmosfera densa?", choices: ["Não, é quase nula", "Sim, como a Terra", "Sim, de oxigênio", "Sim, de fogo"], answer: 0 },
    { level: 2, q: "Quem foi o 2º a pisar na Lua?", choices: ["Buzz Aldrin", "Michael Collins", "Yuri Gagarin", "Glenn"], answer: 0 },
    { level: 2, q: "A Lua sempre mostra à Terra a:", choices: ["Mesma face", "Faces diferentes a cada dia", "Só polos", "Só equador"], answer: 0 },
    { level: 2, q: "A gravidade na Lua é cerca de quantos % da terrestre?", choices: ["~16%", "100%", "200%", "1%"], answer: 0 },
    { level: 2, q: "A bandeira deixada na Lua é dos:", choices: ["EUA", "Brasil", "URSS", "China"], answer: 0 },
    { level: 2, q: "Apollo 11 partiu de qual centro de lançamento?", choices: ["Cabo Canaveral", "Baikonur", "Alcântara", "Tanegashima"], answer: 0 },
    { level: 2, q: "Quantos astronautas pisaram na Lua no total?", choices: ["12", "1", "3", "100"], answer: 0 },
    { level: 2, q: "A Lua se afasta da Terra cerca de:", choices: ["~3,8 cm por ano", "1 km por ano", "Não se afasta", "1 m por dia"], answer: 0 },
    { level: 2, q: "Marés são causadas principalmente por:", choices: ["Lua (e Sol)", "Vento", "Chuva", "Calor"], answer: 0 },
    { level: 3, q: "A 1ª sonda a chegar perto da Lua foi soviética:", choices: ["Luna 1 (1959)", "Apollo 1", "Voyager 1", "Sputnik 1"], answer: 0 },
    { level: 3, q: "Programa Apollo teve quantos pousos tripulados?", choices: ["6", "1", "10", "20"], answer: 0 },
    { level: 3, q: "A última missão Apollo a pousar na Lua foi:", choices: ["Apollo 17", "Apollo 11", "Apollo 1", "Apollo 50"], answer: 0 },
    { level: 3, q: "Quem comandou Apollo 13, que não pousou?", choices: ["Jim Lovell", "Neil Armstrong", "Yuri Gagarin", "Buzz Aldrin"], answer: 0 },
    { level: 3, q: "A teoria mais aceita da origem da Lua é o impacto com:", choices: ["Theia", "Marte", "Mercúrio", "Vênus"], answer: 0 },
    { level: 3, q: "A maior cratera de impacto da Lua é:", choices: ["South Pole-Aitken", "Tycho", "Copernicus", "Hellas"], answer: 0 },
    { level: 3, q: "Que programa da NASA quer voltar à Lua nos anos 2020:", choices: ["Artemis", "Apollo 2.0", "Mercury", "Gemini"], answer: 0 },
    { level: 3, q: "A China pousou rovers no lado afastado da Lua com a missão:", choices: ["Chang'e 4", "Tianwen", "Shenzhou", "Apollo 18"], answer: 0 },
    { level: 3, q: "A Índia colocou rover no polo sul lunar com:", choices: ["Chandrayaan-3 (2023)", "Mangalyaan", "Apollo 11", "Luna 25"], answer: 0 },
    { level: 3, q: "A distância média Terra–Lua é cerca de:", choices: ["~384 mil km", "1 mil km", "1 milhão km", "10 milhões km"], answer: 0 },
  ],
  europa: [
    { level: 1, q: "Europa é uma lua de qual planeta?", choices: ["Marte", "Saturno", "Júpiter", "Netuno"], answer: 2 },
    { level: 1, q: "Europa interessa cientistas porque pode ter:", choices: ["Vulcões de chocolate", "Oceano de água sob o gelo", "Florestas", "Desertos"], answer: 1 },
    { level: 1, q: "A superfície de Europa é coberta principalmente por:", choices: ["Areia", "Gelo", "Lava", "Água líquida exposta"], answer: 1 },
    { level: 1, q: "Europa é uma das quatro luas chamadas:", choices: ["Galileanas", "Pequenas", "Solares", "Lunares"], answer: 0 },
    { level: 1, q: "Europa tem gravidade:", choices: ["Bem menor que a da Terra", "Maior que a da Terra", "Igual à Terra", "Zero"], answer: 0 },
    { level: 1, q: "Europa é maior ou menor que a Lua da Terra?", choices: ["Um pouco menor", "Muito maior", "Igual ao Sol", "Igual a Marte"], answer: 0 },
    { level: 1, q: "Europa pode ter vida microbiana, segundo cientistas?", choices: ["É possível", "Já tem cidade", "Tem dinossauro", "Tem oceano de plástico"], answer: 0 },
    { level: 1, q: "Europa é destino frequente em filmes de:", choices: ["Ficção científica", "Romance", "Comédia romântica", "Musical"], answer: 0 },
    { level: 1, q: "O filme 'Europa Report' é sobre:", choices: ["Astronautas indo a Europa", "Guerra na Europa", "História da União Europeia", "Música pop"], answer: 0 },
    { level: 1, q: "Europa é fria?", choices: ["Sim, muito", "Não, é quente", "Tropical", "Tem deserto"], answer: 0 },
    { level: 2, q: "Quem descobriu Europa no século XVII?", choices: ["Galileu Galilei", "Einstein", "Newton", "Hubble"], answer: 0 },
    { level: 2, q: "Qual missão da NASA estudará Europa nos próximos anos?", choices: ["Europa Clipper", "Voyager 5", "Mars Rover", "Apollo 20"], answer: 0 },
    { level: 2, q: "Europa Clipper foi lançada em:", choices: ["2024", "2010", "2030", "1999"], answer: 0 },
    { level: 2, q: "As outras 3 luas galileanas são Io, Ganimedes e:", choices: ["Calisto", "Titã", "Lua", "Tritão"], answer: 0 },
    { level: 2, q: "Europa orbita Júpiter em quanto tempo (aprox.)?", choices: ["~3,5 dias", "1 ano", "100 dias", "1 hora"], answer: 0 },
    { level: 2, q: "A superfície de Europa é jovem porque:", choices: ["Geologicamente ativa, gelo se renova", "Cheia de cratera antiga", "É de lava recente", "Ninguém sabe explicar"], answer: 0 },
    { level: 2, q: "Em 2001: Uma Odisseia no Espaço 2010, Europa não pode ser:", choices: ["Tocada por humanos", "Olhada", "Estudada", "Mencionada"], answer: 0 },
    { level: 2, q: "A camada de gelo de Europa tem espessura estimada de:", choices: ["Dezenas de km", "1 cm", "1 m", "1000 km"], answer: 0 },
    { level: 2, q: "A energia interna de Europa vem em grande parte de:", choices: ["Marés gravitacionais com Júpiter", "Sol direto", "Fissão nuclear natural", "Vento solar"], answer: 0 },
    { level: 2, q: "Europa pode ter mais água ___ que a Terra.", choices: ["Líquida total", "Em forma de gelo só", "Em forma de gás", "Em forma de fogo"], answer: 0 },
    { level: 3, q: "Europa foi visitada de perto pela sonda:", choices: ["Galileo (NASA)", "Voyager 2", "Cassini", "BepiColombo"], answer: 0 },
    { level: 3, q: "Quem nomeou as 4 luas galileanas?", choices: ["Simon Marius", "Galileu sozinho", "Hubble", "Einstein"], answer: 0 },
    { level: 3, q: "O ano da descoberta das luas galileanas é:", choices: ["1610", "1500", "1700", "1900"], answer: 0 },
    { level: 3, q: "A missão JUICE (ESA) vai estudar luas de:", choices: ["Júpiter", "Saturno", "Marte", "Mercúrio"], answer: 0 },
    { level: 3, q: "Europa tem atmosfera de:", choices: ["Oxigênio finíssimo", "Nitrogênio denso", "Hidrogênio", "Não tem"], answer: 0 },
    { level: 3, q: "O nome Europa vem da mitologia ___ (princesa raptada por Zeus).", choices: ["Grega", "Romana", "Egípcia", "Nórdica"], answer: 0 },
    { level: 3, q: "Europa Clipper vai entrar em órbita de:", choices: ["Júpiter, fazendo passagens por Europa", "Diretamente Europa", "Lua da Terra", "Sol"], answer: 0 },
    { level: 3, q: "Europa tem manchas escuras lineares chamadas:", choices: ["Lineae", "Maria", "Vallis", "Rima"], answer: 0 },
    { level: 3, q: "O diâmetro de Europa é de aproximadamente:", choices: ["~3120 km", "100 km", "30000 km", "1 km"], answer: 0 },
    { level: 3, q: "Europa pode ter plumas de água detectadas pelo:", choices: ["Hubble", "Voyager 1", "James Webb apenas", "Cassini"], answer: 0 },
  ],
};

export function getBankForDestination(destinationId: string): BankQuestion[] {
  return BANK[destinationId] ?? [];
}
