/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthenticatedUpgradesRouteImport } from './routes/_authenticated/upgrades'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedLojaRouteImport } from './routes/_authenticated/loja'
import { Route as AuthenticatedGaleriaRouteImport } from './routes/_authenticated/galeria'
import { Route as AuthenticatedGalaxiaRouteImport } from './routes/_authenticated/galaxia'
import { Route as AuthenticatedEquipesRouteImport } from './routes/_authenticated/equipes'
import { Route as AuthenticatedCriarRouteImport } from './routes/_authenticated/criar'
import { Route as AuthenticatedBatalhaRouteImport } from './routes/_authenticated/batalha'
import { Route as AuthenticatedEquipesDestinosRouteImport } from './routes/_authenticated/equipes.destinos'
import { Route as AuthenticatedBatalhaIdRouteImport } from './routes/_authenticated/batalha.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedEquipesConviteTokenRouteImport } from './routes/_authenticated/equipes.convite.$token'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUpgradesRoute = AuthenticatedUpgradesRouteImport.update({
  id: '/upgrades',
  path: '/upgrades',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLojaRoute = AuthenticatedLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGaleriaRoute = AuthenticatedGaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGalaxiaRoute = AuthenticatedGalaxiaRouteImport.update({
  id: '/galaxia',
  path: '/galaxia',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipesRoute = AuthenticatedEquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCriarRoute = AuthenticatedCriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBatalhaRoute = AuthenticatedBatalhaRouteImport.update({
  id: '/batalha',
  path: '/batalha',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipesDestinosRoute =
  AuthenticatedEquipesDestinosRouteImport.update({
    id: '/destinos',
    path: '/destinos',
    getParentRoute: () => AuthenticatedEquipesRoute,
  } as any)
const AuthenticatedBatalhaIdRoute = AuthenticatedBatalhaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBatalhaRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedEquipesConviteTokenRoute =
  AuthenticatedEquipesConviteTokenRouteImport.update({
    id: '/convite/$token',
    path: '/convite/$token',
    getParentRoute: () => AuthenticatedEquipesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/batalha': typeof AuthenticatedBatalhaRouteWithChildren
  '/criar': typeof AuthenticatedCriarRoute
  '/equipes': typeof AuthenticatedEquipesRouteWithChildren
  '/galaxia': typeof AuthenticatedGalaxiaRoute
  '/galeria': typeof AuthenticatedGaleriaRoute
  '/loja': typeof AuthenticatedLojaRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/upgrades': typeof AuthenticatedUpgradesRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/batalha/$id': typeof AuthenticatedBatalhaIdRoute
  '/equipes/destinos': typeof AuthenticatedEquipesDestinosRoute
  '/equipes/convite/$token': typeof AuthenticatedEquipesConviteTokenRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/batalha': typeof AuthenticatedBatalhaRouteWithChildren
  '/criar': typeof AuthenticatedCriarRoute
  '/equipes': typeof AuthenticatedEquipesRouteWithChildren
  '/galaxia': typeof AuthenticatedGalaxiaRoute
  '/galeria': typeof AuthenticatedGaleriaRoute
  '/loja': typeof AuthenticatedLojaRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/upgrades': typeof AuthenticatedUpgradesRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/batalha/$id': typeof AuthenticatedBatalhaIdRoute
  '/equipes/destinos': typeof AuthenticatedEquipesDestinosRoute
  '/equipes/convite/$token': typeof AuthenticatedEquipesConviteTokenRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/batalha': typeof AuthenticatedBatalhaRouteWithChildren
  '/_authenticated/criar': typeof AuthenticatedCriarRoute
  '/_authenticated/equipes': typeof AuthenticatedEquipesRouteWithChildren
  '/_authenticated/galaxia': typeof AuthenticatedGalaxiaRoute
  '/_authenticated/galeria': typeof AuthenticatedGaleriaRoute
  '/_authenticated/loja': typeof AuthenticatedLojaRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/upgrades': typeof AuthenticatedUpgradesRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/_authenticated/batalha/$id': typeof AuthenticatedBatalhaIdRoute
  '/_authenticated/equipes/destinos': typeof AuthenticatedEquipesDestinosRoute
  '/_authenticated/equipes/convite/$token': typeof AuthenticatedEquipesConviteTokenRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/batalha'
    | '/criar'
    | '/equipes'
    | '/galaxia'
    | '/galeria'
    | '/loja'
    | '/mapa'
    | '/upgrades'
    | '/checkout/return'
    | '/batalha/$id'
    | '/equipes/destinos'
    | '/equipes/convite/$token'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/batalha'
    | '/criar'
    | '/equipes'
    | '/galaxia'
    | '/galeria'
    | '/loja'
    | '/mapa'
    | '/upgrades'
    | '/checkout/return'
    | '/batalha/$id'
    | '/equipes/destinos'
    | '/equipes/convite/$token'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/batalha'
    | '/_authenticated/criar'
    | '/_authenticated/equipes'
    | '/_authenticated/galaxia'
    | '/_authenticated/galeria'
    | '/_authenticated/loja'
    | '/_authenticated/mapa'
    | '/_authenticated/upgrades'
    | '/checkout/return'
    | '/_authenticated/batalha/$id'
    | '/_authenticated/equipes/destinos'
    | '/_authenticated/equipes/convite/$token'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upgrades': {
      id: '/_authenticated/upgrades'
      path: '/upgrades'
      fullPath: '/upgrades'
      preLoaderRoute: typeof AuthenticatedUpgradesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loja': {
      id: '/_authenticated/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof AuthenticatedLojaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/galeria': {
      id: '/_authenticated/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof AuthenticatedGaleriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/galaxia': {
      id: '/_authenticated/galaxia'
      path: '/galaxia'
      fullPath: '/galaxia'
      preLoaderRoute: typeof AuthenticatedGalaxiaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipes': {
      id: '/_authenticated/equipes'
      path: '/equipes'
      fullPath: '/equipes'
      preLoaderRoute: typeof AuthenticatedEquipesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/criar': {
      id: '/_authenticated/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof AuthenticatedCriarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/batalha': {
      id: '/_authenticated/batalha'
      path: '/batalha'
      fullPath: '/batalha'
      preLoaderRoute: typeof AuthenticatedBatalhaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipes/destinos': {
      id: '/_authenticated/equipes/destinos'
      path: '/destinos'
      fullPath: '/equipes/destinos'
      preLoaderRoute: typeof AuthenticatedEquipesDestinosRouteImport
      parentRoute: typeof AuthenticatedEquipesRoute
    }
    '/_authenticated/batalha/$id': {
      id: '/_authenticated/batalha/$id'
      path: '/$id'
      fullPath: '/batalha/$id'
      preLoaderRoute: typeof AuthenticatedBatalhaIdRouteImport
      parentRoute: typeof AuthenticatedBatalhaRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/equipes/convite/$token': {
      id: '/_authenticated/equipes/convite/$token'
      path: '/convite/$token'
      fullPath: '/equipes/convite/$token'
      preLoaderRoute: typeof AuthenticatedEquipesConviteTokenRouteImport
      parentRoute: typeof AuthenticatedEquipesRoute
    }
  }
}

interface AuthenticatedBatalhaRouteChildren {
  AuthenticatedBatalhaIdRoute: typeof AuthenticatedBatalhaIdRoute
}

const AuthenticatedBatalhaRouteChildren: AuthenticatedBatalhaRouteChildren = {
  AuthenticatedBatalhaIdRoute: AuthenticatedBatalhaIdRoute,
}

const AuthenticatedBatalhaRouteWithChildren =
  AuthenticatedBatalhaRoute._addFileChildren(AuthenticatedBatalhaRouteChildren)

interface AuthenticatedEquipesRouteChildren {
  AuthenticatedEquipesDestinosRoute: typeof AuthenticatedEquipesDestinosRoute
  AuthenticatedEquipesConviteTokenRoute: typeof AuthenticatedEquipesConviteTokenRoute
}

const AuthenticatedEquipesRouteChildren: AuthenticatedEquipesRouteChildren = {
  AuthenticatedEquipesDestinosRoute: AuthenticatedEquipesDestinosRoute,
  AuthenticatedEquipesConviteTokenRoute: AuthenticatedEquipesConviteTokenRoute,
}

const AuthenticatedEquipesRouteWithChildren =
  AuthenticatedEquipesRoute._addFileChildren(AuthenticatedEquipesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedBatalhaRoute: typeof AuthenticatedBatalhaRouteWithChildren
  AuthenticatedCriarRoute: typeof AuthenticatedCriarRoute
  AuthenticatedEquipesRoute: typeof AuthenticatedEquipesRouteWithChildren
  AuthenticatedGalaxiaRoute: typeof AuthenticatedGalaxiaRoute
  AuthenticatedGaleriaRoute: typeof AuthenticatedGaleriaRoute
  AuthenticatedLojaRoute: typeof AuthenticatedLojaRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedUpgradesRoute: typeof AuthenticatedUpgradesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBatalhaRoute: AuthenticatedBatalhaRouteWithChildren,
  AuthenticatedCriarRoute: AuthenticatedCriarRoute,
  AuthenticatedEquipesRoute: AuthenticatedEquipesRouteWithChildren,
  AuthenticatedGalaxiaRoute: AuthenticatedGalaxiaRoute,
  AuthenticatedGaleriaRoute: AuthenticatedGaleriaRoute,
  AuthenticatedLojaRoute: AuthenticatedLojaRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedUpgradesRoute: AuthenticatedUpgradesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
